name: Generate Changelog

on:
  push:
    branches:
      - dev  # 根据需要修改分支

permissions:
  contents: write  # 允许写入内容

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for existing CHANGELOG.md
        id: check_changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md does not exist."
            echo "create=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md exists."
            echo "create=false" >> $GITHUB_ENV
          fi

      - name: Generate or Update CHANGELOG.md
        run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          if [ "${{ env.create }}" == "true" ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "## [$CURRENT_DATE] - Initial Release" >> CHANGELOG.md
            # 获取所有提交信息并倒序写入，包含哈希
            git log --reverse --date=short --pretty=format:"- %s (%h)" >> CHANGELOG.md
          else
            echo "Updating existing CHANGELOG.md"
            echo "" >> CHANGELOG.md
            echo "## [$CURRENT_DATE] - Update" >> CHANGELOG.md
            # 获取最新提交信息并写入，包含哈希
            git log -1 --date=short --pretty=format:"- %s (%h)" >> CHANGELOG.md
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with new entries (hash: $(git rev-parse --short HEAD))" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
