name: Update Changelog

on:
  push:
    branches:
      - dev

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current date
        id: current_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get commits
        id: get_commits
        run: |
          if [ -f CHANGELOG.md ]; then
            LAST_UPDATE=$(grep -m 1 "## " CHANGELOG.md | awk '{print $2}' | tr -d '[]')
            git log --since="$LAST_UPDATE" --pretty=format:"- %s" > commits.txt || echo "No new commits"
          else
            git log --pretty=format:"- %s" > commits.txt || echo "No commits found"
          fi

          if [[ -s commits.txt ]]; then
            echo "Commits=$(cat commits.txt)" >> $GITHUB_ENV
          else
            echo "Commits=No new commits" >> $GITHUB_ENV
          fi

      - name: Update or create CHANGELOG.md
        run: |
          if [[ "$(echo ${{ env.Commits }})" != "No new commits" ]]; then
            if [ ! -f CHANGELOG.md ]; then
              echo "# Changelog" > CHANGELOG.md
            fi
            echo "## [${{ env.DATE }}] - Update" >> CHANGELOG.md
            echo "${{ env.Commits }}" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

      - name: Create a new branch
        run: |
          git checkout -b update-changelog

      - name: Commit changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with latest commits on ${{ env.DATE }}" || echo "No changes to commit"

      - name: Push changes to remote
        run: |
          git push origin update-changelog

      - name: Check for open PR from GitHub Action bot
        id: check_pr
        run: |
          OPEN_PR=$(gh pr list --base dev --state open --json author --jq '[.[] | select(.author.login == "github-actions[bot]")] | length')
          echo "OPEN_PR=$OPEN_PR" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.OPEN_PR == '0'
        run: |
          gh pr create --title "Update CHANGELOG.md" --body "This PR updates the CHANGELOG with the latest commits." --base dev --head update-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup branch (optional)
        if: github.event.action == 'closed'
        run: |
          git branch -D update-changelog
