name: Update CHANGELOG

on:
  push:
    branches:
      - main
permissions:
  contents: write  # 允许写入仓库内容，必要用于更新 CHANGELOG.md


jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Generate CHANGELOG
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # Create a temporary file to hold the commit logs
          TEMP_FILE=$(mktemp)

          # Get all commits in reverse order (oldest first)
          git log --no-merges --pretty=format:"%ad | %h | %s" --date=format:'%Y-%m-%d' > "$TEMP_FILE"

          # Read the temporary file and format the changelog
          while IFS=' | ' read -r date hash message; do
            if [[ $current_date != $date ]]; then
              current_date=$date
              echo "## $current_date" >> CHANGELOG.md
            fi
            echo "- $message (commit: $hash)" >> CHANGELOG.md
          done < "$TEMP_FILE"

          # Clean up temporary file
          rm "$TEMP_FILE"

          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
