name: Update Changelog

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get commits
        id: get_commits
        run: |
          if [ -f CHANGELOG.md ]; then
            LAST_UPDATE=$(grep -m 1 "## " CHANGELOG.md | awk '{print $2}' | tr -d '[]')
            git log --since="$LAST_UPDATE" --pretty=format:"- %s" > commits.txt || echo "No new commits"
          else
            # 直接获取所有提交，并确保格式正确
            git log --pretty=format:"- %s" --reverse > commits.txt || echo "No commits found"
          fi

          if [[ -s commits.txt ]]; then
            echo "Commits=$(cat commits.txt)" >> $GITHUB_ENV
          else
            echo "Commits=No new commits" >> $GITHUB_ENV
          fi


      - name: Update or create CHANGELOG.md
        run: |
          if [[ "$(echo ${{ env.Commits }})" != "No new commits" ]]; then
            if [ ! -f CHANGELOG.md ]; then
              echo "# Changelog" > CHANGELOG.md
            fi

            # 分组提交，并按时间降序排列
            echo "${{ env.Commits }}" | awk -F ' - ' '
            {
              date=$1; 
              commit=$2;
              commits[date] = (commits[date] ? commits[date] ORS : "") "- " commit;
            }
            END {
              n = asorti(commits, dates);
              for (i = n; i > 0; i--) {
                print "## [" dates[i] "] - Update";
                print commits[dates[i]];
                print "";
              }
            }' >> CHANGELOG.md  # 直接追加到 CHANGELOG.md
          fi

      - name: Commit and Push Changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with latest commits $(git rev-parse --short HEAD) (PR #${{ github.event.pull_request.number }})" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Passer1072/RookieAI_yolov8 HEAD:dev
